id: A7977FF7F
title: 'Prayer to Tārā: A Sevenfold Supplication for Protection'
type: translation
pechas:
- I55425E39
- I98704F89
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:45:35.826111
  last_modified_at: 2023-01-04 11:45:35.826122
  collections:
  - Drikung Kyobpa Jikten Sumgön
  - Works of Tibetan Masters
alignment_to_base:
  I55425E39/93D9: '4341'
  I98704F89/34D3: '4341'
